FROM nvcr.io/nvidia/pytorch:18.12-py3

RUN pip install albumentations==0.4.3
RUN pip install pretrainedmodels==0.7.4
RUN pip install pandas
RUN pip install sklearn
RUN pip install pydicom
RUN pip install addict